name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga

  build:
    name: Build
    runs-on: Ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.5']
        composer: ['']
        phpunit: ['SYMFONY_PHPUNIT_VERSION=12']
        deprecation: ['']
        symfony: ['^8.0']
        stability: ['']
        include:
          # symfony version
          - php: 8.4
            symfony: '^8.0'
            phpunit: SYMFONY_PHPUNIT_VERSION=12

          # dev
          - php: 8.5
            stability: 'dev'
            phpunit: SYMFONY_PHPUNIT_VERSION=12

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: flex

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup stability
        if: matrix.stability != ''
        run: composer config minimum-stability "${{ matrix.stability }}"

      - name: Setup deprecation
        if: matrix.deprecation != ''
        run: echo 'SYMFONY_DEPRECATIONS_HELPER=${{ matrix.deprecation }}' >> $GITHUB_ENV

      - name: Setup symfony
        if: matrix.symfony != ''
        run: |
          echo 'SYMFONY_REQUIRE=${{ matrix.symfony }}' >> $GITHUB_ENV

      - name: Download dependencies
        run: |
          composer update ${{ matrix.composer}} --prefer-dist --no-interaction
          ./vendor/bin/simple-phpunit install

      - name: Validate
        run: |
            composer validate --strict --no-check-lock

      - name: Run tests
        env:
          SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT: 1
        run: |
          ${{ matrix.phpunit }} ./vendor/bin/simple-phpunit
